# frozen_string_literal: true

class CreateTomProjectMetricsTrains < ActiveRecord::Migration[6.1]
  def change
    create_table :tom_project_metrics_trains do |t|
      t.string :repo_fullname
      t.integer :commits_count
      t.integer :commits_days_since_first
      t.integer :commits_days_since_last
      t.integer :commits_total_lines_added
      t.integer :commits_total_lines_removed
      t.float :commits_avg_added
      t.float :commits_avg_removed
      t.float :commits_avg_files_changed
      t.float :commits_avg_message_length
      t.float :commits_avg_per_day
      t.float :commits_avg_per_day_real
      t.integer :commits_max_per_day
      t.integer :contributors_count
      t.float :contributors_top_avg_commits
      t.float :contributors_top_avg_participation_week
      t.float :contributors_top_avg_additions
      t.float :contributors_top_avg_deletions
      t.integer :forks_count
      t.float :forks_avg_per_day
      t.float :forks_avg_max_per_day
      t.integer :issues_total_comments
      t.integer :issues_count
      t.integer :issues_open
      t.integer :issues_labels
      t.float :issues_avg_labels
      t.float :issues_avg_closing_time
      t.float :issues_avg_comment_time
      t.float :issues_avg_comments
      t.float :issues_avg_comment_length
      t.float :issues_avg_title_length
      t.float :issues_avg_body_length
      t.float :issues_avg_per_day
      t.float :issues_avg_per_day_real
      t.float :issues_max_per_day
      t.integer :repo_size
      t.integer :repo_topics
      t.integer :repo_branches
      t.integer :repo_age_days
      t.integer :repo_workflows
      t.integer :repo_languages
      t.integer :repo_milestones
      t.integer :repo_watchers
      t.integer :repo_deployments
      t.integer :repo_readme_length
      t.integer :repo_network_members
      t.integer :pulls_count
      t.integer :pulls_total_lines_added
      t.integer :pulls_total_lines_removed
      t.float :pulls_avg_lines_added
      t.float :pulls_avg_lines_removed
      t.float :pulls_avg_closing_time
      t.float :pulls_avg_comments
      t.float :pulls_avg_review_comments
      t.float :pulls_avg_Commits
      t.float :pulls_avg_body_length
      t.float :pulls_avg_title_length
      t.float :pulls_avg_files_changed
      t.float :pulls_avg_labels
      t.float :pulls_avg_created_per_day
      t.float :pulls_avg_created_per_day_real
      t.integer :pulls_max_created_per_day
      t.integer :releases_count
      t.integer :releases_tags
      t.integer :releases_total_downloads
      t.float :releases_avg_body_length
      t.float :releases_avg_title_length
      t.float :releases_avg_assets
      t.float :releases_avg_assets_downloads
      t.float :releases_avg_assets_size
      t.float :releases_avg_downloads_per_day
      t.integer :stars_count
      t.float :stars_avg_per_day_real
      t.integer :stars_max_per_day
      t.integer :wf_count
      t.float :wf_avg_duration
      t.float :wf_avg_success_duration
      t.float :wf_avg_failure_duration
      t.float :wf_avg_successes_per_day
      t.float :wf_avg_successes_per_day_real
      t.float :wf_avg_fails_per_day
      t.timestamps
      t.string :data_label
    end
  end
end
